import { ReloadCard } from "@/components/admin/reload-card";
import { SyncCard } from "@/components/admin/sync-card";
import { PackageList } from "@/components/admin/package-list";
import { AutoGeneratedCard } from "@/components/admin/auto-generated-card";

export default function AdminPage() {
  return (
    <div className="space-y-6">
      <div className="grid gap-6 lg:grid-cols-2">
        <ReloadCard />
        <SyncCard />
      </div>
      <PackageList />
      <AutoGeneratedCard />
    </div>
  );
}
