import { useState } from "react";
import { SyncCard } from "@/components/admin/sync-card";
import { PackageList } from "@/components/admin/package-list";
import { AutoGeneratedCard } from "@/components/admin/auto-generated-card";
import { SchematronRulesManager } from "@/components/admin/schematron-rules-manager";
import { AssetVersionHistory } from "@/components/admin/asset-version-history";
import { DefaultXsltManager } from "@/components/admin/default-xslt-manager";
import { Download, ShieldCheck, Package, FileCode2 } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { motion } from "framer-motion";

const tabs = [
  { id: "sync", label: "GİB Sync", icon: Download },
  { id: "xslt", label: "XSLT Şablonları", icon: FileCode2 },
  { id: "rules", label: "Kurallar", icon: ShieldCheck },
  { id: "packages", label: "Paketler", icon: Package },
] as const;

type TabId = (typeof tabs)[number]["id"];

const fade = {
  hidden: { opacity: 0, y: 12 },
  show: { opacity: 1, y: 0, transition: { duration: 0.4 } },
};

export default function AdminPage() {
  const [activeTab, setActiveTab] = useState<TabId>("sync");

  return (
    <div className="space-y-8">
      <Tabs
        value={activeTab}
        onValueChange={(value) => setActiveTab(value as TabId)}
        className="space-y-8"
      >
        <TabsList variant="pill" className="w-full grid grid-cols-2 sm:grid-cols-4">
          {tabs.map((tab) => {
            const Icon = tab.icon;
            const isActive = activeTab === tab.id;
            return (
              <TabsTrigger key={tab.id} value={tab.id}>
                <Icon className="h-4 w-4" />
                <span className="hidden sm:inline">{tab.label}</span>
                {isActive && (
                  <Badge variant="secondary" className="ml-1 h-4 min-w-5 px-1 text-[10px]">
                    <span className="size-1.5 rounded-full bg-emerald-400 animate-pulse" />
                  </Badge>
                )}
              </TabsTrigger>
            );
          })}
        </TabsList>

        <TabsContent value="sync" asChild>
          <motion.div variants={fade} initial="hidden" animate="show" className="space-y-6">
            <SyncCard />
            <AssetVersionHistory />
          </motion.div>
        </TabsContent>

        <TabsContent value="xslt" asChild>
          <motion.div variants={fade} initial="hidden" animate="show">
            <DefaultXsltManager />
          </motion.div>
        </TabsContent>

        <TabsContent value="rules" asChild>
          <motion.div variants={fade} initial="hidden" animate="show">
            <SchematronRulesManager />
          </motion.div>
        </TabsContent>

        <TabsContent value="packages" asChild>
          <motion.div variants={fade} initial="hidden" animate="show" className="space-y-6">
            <PackageList />
            <AutoGeneratedCard />
          </motion.div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
