package io.mersel.services.xslt.infrastructure;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;

import static org.assertj.core.api.Assertions.assertThat;
import static org.awaitility.Awaitility.await;
import static org.mockito.Mockito.*;

/**
 * AssetFileWatcher birim testleri.
 */
@DisplayName("AssetFileWatcher")
class AssetFileWatcherTest {

    @TempDir
    Path tempDir;

    private AssetRegistry assetRegistry;

    @BeforeEach
    void setUp() {
        assetRegistry = mock(AssetRegistry.class);
    }

    @Test
    @DisplayName("auto_generated_dizini_ignore — auto-generated/ altındaki path'ler yok sayılmalı")
    void auto_generated_dizini_ignore() {
        Path rootDir = tempDir.resolve("assets");
        Path autoGeneratedFile = rootDir.resolve("auto-generated").resolve("schema-overrides").resolve("test.xsd");
        Path normalFile = rootDir.resolve("validator").resolve("schema").resolve("main.xsd");

        assertThat(AssetFileWatcher.isUnderAutoGenerated(rootDir, autoGeneratedFile)).isTrue();
        assertThat(AssetFileWatcher.isUnderAutoGenerated(rootDir, rootDir.resolve("auto-generated"))).isTrue();
        assertThat(AssetFileWatcher.isUnderAutoGenerated(rootDir, rootDir.resolve("auto-generated").resolve("foo"))).isTrue();

        assertThat(AssetFileWatcher.isUnderAutoGenerated(rootDir, normalFile)).isFalse();
        assertThat(AssetFileWatcher.isUnderAutoGenerated(rootDir, rootDir.resolve("validator"))).isFalse();
        assertThat(AssetFileWatcher.isUnderAutoGenerated(rootDir, rootDir.resolve("other-dir"))).isFalse();
    }

    @Test
    @DisplayName("debounce_coklu_event — Çoklu hızlı event tek reload tetiklemeli")
    void debounce_coklu_event() throws Exception {
        Path watchDir = tempDir.resolve("watch");
        Files.createDirectories(watchDir);

        AssetFileWatcher watcher = new AssetFileWatcher(assetRegistry, 100, watchDir.toString());
        watcher.init();

        try {
            await().pollDelay(Duration.ofMillis(100)).until(() -> true);
            for (int i = 0; i < 5; i++) {
                Files.writeString(watchDir.resolve("file" + i + ".xml"), "content" + i);
            }
            await().atMost(Duration.ofSeconds(5)).untilAsserted(() ->
                    verify(assetRegistry, atLeastOnce()).reload());
        } finally {
            watcher.shutdown();
        }
    }

    @Test
    @DisplayName("dosya_degisikligi_reload_tetikler — Normal dosya değişikliği reload tetiklemeli")
    void dosya_degisikligi_reload_tetikler() throws Exception {
        Path watchDir = tempDir.resolve("watch");
        Files.createDirectories(watchDir);

        AssetFileWatcher watcher = new AssetFileWatcher(assetRegistry, 100, watchDir.toString());
        watcher.init();

        try {
            await().pollDelay(Duration.ofMillis(150)).until(() -> true);
            Files.writeString(watchDir.resolve("test.xml"), "<xml/>");
            await().atMost(Duration.ofSeconds(5)).untilAsserted(() ->
                    verify(assetRegistry, atLeastOnce()).reload());
        } finally {
            watcher.shutdown();
        }
    }
}
