import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AXIOS_INSTANCE, customInstance } from "./axios-instance";
import type {
  XsltServiceResponse,
  ValidationResponse,
  TransformResult,
  TransformMeta,
  ReloadResponse,
  ProfilesResponse,
  SyncResponse,
  PackagesResponse,
  AutoGeneratedResponse,
  SchematronRulesResponse,
  SyncPreviewResponse,
  AssetVersionListResponse,
  PendingPreviewsResponse,
  FileDiffDetail,
  ApproveResponse,
  VersionDiffResponse,
  DefaultXsltListResponse,
  DefaultXsltContentResponse,
  DefaultXsltSaveResponse,
} from "./types";

// ─── Validation ─────────────────────────────────────────────────────

interface ValidateParams {
  source: File;
  ublTrMainSchematronType?: string;
  profile?: string;
  suppressions?: string;
}

export function useValidate() {
  return useMutation({
    mutationFn: async (params: ValidateParams) => {
      const formData = new FormData();
      formData.append("source", params.source);
      if (params.ublTrMainSchematronType) {
        formData.append(
          "ublTrMainSchematronType",
          params.ublTrMainSchematronType
        );
      }
      if (params.profile) {
        formData.append("profile", params.profile);
      }
      if (params.suppressions) {
        formData.append("suppressions", params.suppressions);
      }

      return customInstance<XsltServiceResponse<ValidationResponse>>({
        url: "/v1/validate",
        method: "POST",
        data: formData,
        headers: { "Content-Type": "multipart/form-data" },
      });
    },
  });
}

// ─── Transform ──────────────────────────────────────────────────────

interface TransformParams {
  document: File;
  transformType: string;
  watermarkText?: string;
  transformer?: File;
  useEmbeddedXslt?: boolean;
}

export function useTransform() {
  return useMutation({
    mutationFn: async (params: TransformParams): Promise<TransformResult> => {
      const formData = new FormData();
      formData.append("document", params.document);
      formData.append("transformType", params.transformType);
      if (params.watermarkText) {
        formData.append("watermarkText", params.watermarkText);
      }
      if (params.transformer) {
        formData.append("transformer", params.transformer);
      }
      if (params.useEmbeddedXslt !== undefined) {
        formData.append("useEmbeddedXslt", String(params.useEmbeddedXslt));
      }

      // Use raw axios to access response headers
      const response = await AXIOS_INSTANCE.post("/v1/transform", formData, {
        headers: { "Content-Type": "multipart/form-data" },
        responseType: "text",
      });

      const headers = response.headers;
      const meta: TransformMeta = {
        defaultUsed: headers["x-xslt-default-used"] === "true",
        embeddedUsed: headers["x-xslt-embedded-used"] === "true",
        customError: headers["x-xslt-custom-error"] || undefined,
        durationMs: parseInt(headers["x-xslt-duration-ms"] || "0", 10),
        watermarkApplied: headers["x-xslt-watermark-applied"] === "true",
        outputSize: parseInt(headers["x-xslt-output-size"] || "0", 10),
      };

      return { html: response.data as string, meta };
    },
  });
}

// ─── Admin: Reload ──────────────────────────────────────────────────

export function useReloadAssets() {
  return useMutation({
    mutationFn: () =>
      customInstance<ReloadResponse>({
        url: "/v1/admin/assets/reload",
        method: "POST",
      }),
  });
}

// ─── Admin: Profiles ────────────────────────────────────────────────

export function useProfiles(options?: { enabled?: boolean }) {
  return useQuery({
    queryKey: ["profiles"],
    queryFn: () =>
      customInstance<ProfilesResponse>({
        url: "/v1/admin/profiles",
        method: "GET",
      }),
    retry: false, // 401'de gereksiz yeniden deneme yapma
    ...options,
  });
}

// ─── Admin: GIB Sync ────────────────────────────────────────────────

export function useSyncPackages() {
  return useMutation({
    mutationFn: (packageId?: string) =>
      customInstance<SyncResponse>({
        url: "/v1/admin/packages/sync",
        method: "POST",
        params: packageId ? { package: packageId } : undefined,
      }),
  });
}

// ─── Admin: Packages ────────────────────────────────────────────────

export function usePackages() {
  return useQuery({
    queryKey: ["packages"],
    queryFn: () =>
      customInstance<PackagesResponse>({
        url: "/v1/admin/packages",
        method: "GET",
      }),
  });
}

// ─── Admin: Auto-Generated ──────────────────────────────────────────

export function useAutoGenerated() {
  return useQuery({
    queryKey: ["auto-generated"],
    queryFn: () =>
      customInstance<AutoGeneratedResponse>({
        url: "/v1/admin/auto-generated",
        method: "GET",
      }),
  });
}

// ─── Admin: Global Schematron Rules ─────────────────────────────────

export function useSchematronRules(options?: { enabled?: boolean }) {
  return useQuery({
    queryKey: ["schematron-rules"],
    queryFn: () =>
      customInstance<SchematronRulesResponse>({
        url: "/v1/admin/schematron-rules",
        method: "GET",
      }),
    retry: false,
    ...options,
  });
}

export function useSaveSchematronRules() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (
      rules: Record<
        string,
        { context: string; test: string; message: string; id?: string }[]
      >
    ) =>
      customInstance({
        url: "/v1/admin/schematron-rules",
        method: "PUT",
        data: { rules },
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["schematron-rules"] });
      queryClient.invalidateQueries({ queryKey: ["auto-generated"] });
    },
  });
}

// ─── Admin: Sync Preview (Versioning) ────────────────────────────────

export function useSyncPreview() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (packageId?: string) =>
      customInstance<SyncPreviewResponse>({
        url: "/v1/admin/packages/sync-preview",
        method: "POST",
        params: packageId ? { package: packageId } : undefined,
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["pending-previews"] });
    },
  });
}

export function useAssetVersions(packageId?: string) {
  return useQuery({
    queryKey: ["asset-versions", packageId],
    queryFn: () =>
      customInstance<AssetVersionListResponse>({
        url: "/v1/admin/asset-versions",
        method: "GET",
        params: packageId ? { packageId } : undefined,
      }),
    retry: false,
  });
}

export function usePendingPreviews() {
  return useQuery({
    queryKey: ["pending-previews"],
    queryFn: () =>
      customInstance<PendingPreviewsResponse>({
        url: "/v1/admin/asset-versions/pending",
        method: "GET",
      }),
    retry: false,
    refetchInterval: 10000,
  });
}

export function usePendingFileDiff(packageId: string, filePath: string) {
  return useQuery({
    queryKey: ["pending-file-diff", packageId, filePath],
    queryFn: () =>
      customInstance<FileDiffDetail>({
        url: `/v1/admin/asset-versions/pending/${encodeURIComponent(packageId)}/file-diff`,
        method: "GET",
        params: { path: filePath },
      }),
    enabled: !!packageId && !!filePath,
    retry: false,
  });
}

export function useApprovePending() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (packageId: string) =>
      customInstance<ApproveResponse>({
        url: `/v1/admin/asset-versions/pending/${encodeURIComponent(packageId)}/approve`,
        method: "POST",
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["pending-previews"] });
      queryClient.invalidateQueries({ queryKey: ["asset-versions"] });
      queryClient.invalidateQueries({ queryKey: ["auto-generated"] });
      queryClient.invalidateQueries({ queryKey: ["packages"] });
    },
  });
}

export function useRejectPending() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (packageId: string) =>
      customInstance({
        url: `/v1/admin/asset-versions/pending/${encodeURIComponent(packageId)}`,
        method: "DELETE",
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["pending-previews"] });
      queryClient.invalidateQueries({ queryKey: ["asset-versions"] });
    },
  });
}

export function useVersionDiffSummary(versionId: string) {
  return useQuery({
    queryKey: ["version-diff-summary", versionId],
    queryFn: () =>
      customInstance<VersionDiffResponse>({
        url: `/v1/admin/asset-versions/${encodeURIComponent(versionId)}/diff`,
        method: "GET",
      }),
    enabled: !!versionId,
    retry: false,
  });
}

export function useVersionFileDiff(versionId: string, filePath: string) {
  return useQuery({
    queryKey: ["version-file-diff", versionId, filePath],
    queryFn: () =>
      customInstance<FileDiffDetail>({
        url: `/v1/admin/asset-versions/${encodeURIComponent(versionId)}/file-diff`,
        method: "GET",
        params: { path: filePath },
      }),
    enabled: !!versionId && !!filePath,
    retry: false,
  });
}

// ─── Admin: Default XSLT Templates ──────────────────────────────────

export function useDefaultXsltTemplates() {
  return useQuery({
    queryKey: ["default-xslt"],
    queryFn: () =>
      customInstance<DefaultXsltListResponse>({
        url: "/v1/admin/default-xslt",
        method: "GET",
      }),
    retry: false,
  });
}

export function useDefaultXsltContent(transformType: string) {
  return useQuery({
    queryKey: ["default-xslt-content", transformType],
    queryFn: () =>
      customInstance<DefaultXsltContentResponse>({
        url: `/v1/admin/default-xslt/${encodeURIComponent(transformType)}`,
        method: "GET",
      }),
    enabled: !!transformType,
    retry: false,
  });
}

export function useUploadDefaultXslt() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({
      transformType,
      file,
    }: {
      transformType: string;
      file: File;
    }) => {
      const formData = new FormData();
      formData.append("file", file);
      return customInstance<DefaultXsltSaveResponse>({
        url: `/v1/admin/default-xslt/${encodeURIComponent(transformType)}`,
        method: "PUT",
        data: formData,
        headers: { "Content-Type": "multipart/form-data" },
      });
    },
    onSuccess: (_data, variables) => {
      queryClient.invalidateQueries({ queryKey: ["default-xslt"] });
      queryClient.invalidateQueries({
        queryKey: ["default-xslt-content", variables.transformType],
      });
    },
  });
}

export function useSaveDefaultXsltContent() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({
      transformType,
      content,
    }: {
      transformType: string;
      content: string;
    }) =>
      customInstance<DefaultXsltSaveResponse>({
        url: `/v1/admin/default-xslt/${encodeURIComponent(transformType)}/content`,
        method: "PUT",
        data: { content },
      }),
    onSuccess: (_data, variables) => {
      queryClient.invalidateQueries({ queryKey: ["default-xslt"] });
      queryClient.invalidateQueries({
        queryKey: ["default-xslt-content", variables.transformType],
      });
    },
  });
}

export function useDeleteDefaultXslt() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (transformType: string) =>
      customInstance({
        url: `/v1/admin/default-xslt/${encodeURIComponent(transformType)}`,
        method: "DELETE",
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["default-xslt"] });
    },
  });
}

// ─── Admin: Profile CRUD ────────────────────────────────────────────

interface SaveProfileParams {
  name: string;
  description?: string;
  extendsProfile?: string;
  suppressions?: {
    match: string;
    pattern: string;
    scope?: string[];
    description?: string;
  }[];
  xsdOverrides?: Record<
    string,
    { element: string; minOccurs?: string; maxOccurs?: string }[]
  >;
  schematronRules?: Record<
    string,
    { context: string; test: string; message: string; id?: string }[]
  >;
}

export function useSaveProfile() {
  return useMutation({
    mutationFn: (params: SaveProfileParams) =>
      customInstance({
        url: `/v1/admin/profiles/${encodeURIComponent(params.name)}`,
        method: "PUT",
        data: {
          description: params.description ?? "",
          extendsProfile: params.extendsProfile ?? null,
          suppressions: params.suppressions ?? [],
          xsdOverrides: params.xsdOverrides ?? {},
          schematronRules: params.schematronRules ?? {},
        },
      }),
  });
}

export function useDeleteProfile() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (profileName: string) =>
      customInstance({
        url: `/v1/admin/profiles/${encodeURIComponent(profileName)}`,
        method: "DELETE",
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["profiles"] });
    },
  });
}
