import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AXIOS_INSTANCE, customInstance } from "./axios-instance";
import type {
  XsltServiceResponse,
  ValidationResponse,
  TransformResult,
  TransformMeta,
  ReloadResponse,
  ProfilesResponse,
  SyncResponse,
  PackagesResponse,
  AutoGeneratedResponse,
  SchematronRulesResponse,
} from "./types";

// ─── Validation ─────────────────────────────────────────────────────

interface ValidateParams {
  source: File;
  ublTrMainSchematronType?: string;
  profile?: string;
  suppressions?: string;
}

export function useValidate() {
  return useMutation({
    mutationFn: async (params: ValidateParams) => {
      const formData = new FormData();
      formData.append("source", params.source);
      if (params.ublTrMainSchematronType) {
        formData.append(
          "ublTrMainSchematronType",
          params.ublTrMainSchematronType
        );
      }
      if (params.profile) {
        formData.append("profile", params.profile);
      }
      if (params.suppressions) {
        formData.append("suppressions", params.suppressions);
      }

      return customInstance<XsltServiceResponse<ValidationResponse>>({
        url: "/v1/validate",
        method: "POST",
        data: formData,
        headers: { "Content-Type": "multipart/form-data" },
      });
    },
  });
}

// ─── Transform ──────────────────────────────────────────────────────

interface TransformParams {
  document: File;
  transformType: string;
  watermarkText?: string;
  transformer?: File;
  useEmbeddedXslt?: boolean;
}

export function useTransform() {
  return useMutation({
    mutationFn: async (params: TransformParams): Promise<TransformResult> => {
      const formData = new FormData();
      formData.append("document", params.document);
      formData.append("transformType", params.transformType);
      if (params.watermarkText) {
        formData.append("watermarkText", params.watermarkText);
      }
      if (params.transformer) {
        formData.append("transformer", params.transformer);
      }
      if (params.useEmbeddedXslt !== undefined) {
        formData.append("useEmbeddedXslt", String(params.useEmbeddedXslt));
      }

      // Use raw axios to access response headers
      const response = await AXIOS_INSTANCE.post("/v1/transform", formData, {
        headers: { "Content-Type": "multipart/form-data" },
        responseType: "text",
      });

      const headers = response.headers;
      const meta: TransformMeta = {
        defaultUsed: headers["x-xslt-default-used"] === "true",
        embeddedUsed: headers["x-xslt-embedded-used"] === "true",
        customError: headers["x-xslt-custom-error"] || undefined,
        durationMs: parseInt(headers["x-xslt-duration-ms"] || "0", 10),
        watermarkApplied: headers["x-xslt-watermark-applied"] === "true",
        outputSize: parseInt(headers["x-xslt-output-size"] || "0", 10),
      };

      return { html: response.data as string, meta };
    },
  });
}

// ─── Admin: Reload ──────────────────────────────────────────────────

export function useReloadAssets() {
  return useMutation({
    mutationFn: () =>
      customInstance<ReloadResponse>({
        url: "/v1/admin/assets/reload",
        method: "POST",
      }),
  });
}

// ─── Admin: Profiles ────────────────────────────────────────────────

export function useProfiles(options?: { enabled?: boolean }) {
  return useQuery({
    queryKey: ["profiles"],
    queryFn: () =>
      customInstance<ProfilesResponse>({
        url: "/v1/admin/profiles",
        method: "GET",
      }),
    retry: false, // 401'de gereksiz yeniden deneme yapma
    ...options,
  });
}

// ─── Admin: GIB Sync ────────────────────────────────────────────────

export function useSyncPackages() {
  return useMutation({
    mutationFn: (packageId?: string) =>
      customInstance<SyncResponse>({
        url: "/v1/admin/packages/sync",
        method: "POST",
        params: packageId ? { package: packageId } : undefined,
      }),
  });
}

// ─── Admin: Packages ────────────────────────────────────────────────

export function usePackages() {
  return useQuery({
    queryKey: ["packages"],
    queryFn: () =>
      customInstance<PackagesResponse>({
        url: "/v1/admin/packages",
        method: "GET",
      }),
  });
}

// ─── Admin: Auto-Generated ──────────────────────────────────────────

export function useAutoGenerated() {
  return useQuery({
    queryKey: ["auto-generated"],
    queryFn: () =>
      customInstance<AutoGeneratedResponse>({
        url: "/v1/admin/auto-generated",
        method: "GET",
      }),
  });
}

// ─── Admin: Global Schematron Rules ─────────────────────────────────

export function useSchematronRules(options?: { enabled?: boolean }) {
  return useQuery({
    queryKey: ["schematron-rules"],
    queryFn: () =>
      customInstance<SchematronRulesResponse>({
        url: "/v1/admin/schematron-rules",
        method: "GET",
      }),
    retry: false,
    ...options,
  });
}

export function useSaveSchematronRules() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (
      rules: Record<
        string,
        { context: string; test: string; message: string; id?: string }[]
      >
    ) =>
      customInstance({
        url: "/v1/admin/schematron-rules",
        method: "PUT",
        data: { rules },
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["schematron-rules"] });
      queryClient.invalidateQueries({ queryKey: ["auto-generated"] });
    },
  });
}

// ─── Admin: Profile CRUD ────────────────────────────────────────────

interface SaveProfileParams {
  name: string;
  description?: string;
  extendsProfile?: string;
  suppressions?: {
    match: string;
    pattern: string;
    scope?: string[];
    description?: string;
  }[];
  xsdOverrides?: Record<
    string,
    { element: string; minOccurs?: string; maxOccurs?: string }[]
  >;
  schematronRules?: Record<
    string,
    { context: string; test: string; message: string; id?: string }[]
  >;
}

export function useSaveProfile() {
  return useMutation({
    mutationFn: (params: SaveProfileParams) =>
      customInstance({
        url: `/v1/admin/profiles/${encodeURIComponent(params.name)}`,
        method: "PUT",
        data: {
          description: params.description ?? "",
          extendsProfile: params.extendsProfile ?? null,
          suppressions: params.suppressions ?? [],
          xsdOverrides: params.xsdOverrides ?? {},
          schematronRules: params.schematronRules ?? {},
        },
      }),
  });
}

export function useDeleteProfile() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (profileName: string) =>
      customInstance({
        url: `/v1/admin/profiles/${encodeURIComponent(profileName)}`,
        method: "DELETE",
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["profiles"] });
    },
  });
}
