import { Badge } from "@/components/ui/badge";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import {
  Cpu,
  FileCode2,
  FileText,
  ScrollText,
  FolderOpen,
  CheckCircle2,
  AlertCircle,
} from "lucide-react";
import { Skeleton } from "@/components/ui/skeleton";
import { useAutoGenerated } from "@/api/hooks";

export function AutoGeneratedCard() {
  const { data, isLoading, error } = useAutoGenerated();

  const categories = data
    ? [
        {
          key: "schematron",
          label: "Schematron XSLT",
          description: "ISO pipeline ile derlenen Schematron XSLT çıktıları",
          icon: FileCode2,
          data: data.schematron,
        },
        {
          key: "schemaOverrides",
          label: "XSD Override",
          description: "Profil bazlı override uygulanmış XSD dosyaları",
          icon: FileText,
          data: data.schemaOverrides,
        },
        {
          key: "schematronRules",
          label: "Özel Schematron Kuralları",
          description: "Profil bazlı ek Schematron kuralları ile derlenmiş XSLT çıktıları",
          icon: ScrollText,
          data: data.schematronRules,
        },
      ]
    : [];

  return (
    <div className="rounded-xl border bg-card shadow-xs overflow-hidden">
      <div className="p-5">
        <div className="flex items-start justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-muted text-foreground/70">
              <Cpu className="h-4 w-4" />
            </div>
            <div>
              <h3 className="text-sm font-semibold">Derlenmiş Dosyalar</h3>
              <p className="text-xs text-muted-foreground mt-0.5">
                Pipeline ve override sonrası üretilen auto-generated dosyalar
              </p>
            </div>
          </div>
          {data && (
            <Badge
              variant={data.totalCount > 0 ? "default" : "secondary"}
              className="rounded-md shrink-0"
            >
              {data.totalCount} dosya
            </Badge>
          )}
        </div>
      </div>

      <div className="border-t bg-muted/20 p-4">
        {error ? (
          <div className="rounded-lg border border-dashed border-destructive/30 bg-destructive/5 p-3 text-xs text-destructive flex items-start gap-2">
            <AlertCircle className="h-3.5 w-3.5 shrink-0 mt-0.5" />
            <span>Derlenmiş dosya bilgileri yüklenirken hata oluştu.</span>
          </div>
        ) : isLoading ? (
          <div className="space-y-4 p-5">
            {[1, 2].map((i) => (
              <div key={i} className="flex items-center gap-3 p-3 rounded-lg border bg-card">
                <Skeleton className="h-8 w-8 rounded-lg shrink-0" />
                <div className="space-y-2 flex-1">
                  <Skeleton className="h-4 w-2/5" />
                  <Skeleton className="h-3 w-3/5" />
                </div>
              </div>
            ))}
          </div>
        ) : !data || data.totalCount === 0 ? (
          <div className="rounded-lg border border-dashed border-warning/30 bg-warning/5 p-3 text-xs text-warning flex items-start gap-2">
            <AlertCircle className="h-3.5 w-3.5 shrink-0 mt-0.5" />
            <span>
              Henüz derlenmiş dosya yok. Asset reload yapıldıktan sonra
              Schematron pipeline çıktıları burada görünecek.
            </span>
          </div>
        ) : (
          <Accordion type="single" collapsible className="w-full space-y-2">
            {categories.map((cat) => (
              <AccordionItem
                key={cat.key}
                value={cat.key}
                className="border rounded-lg bg-card overflow-hidden"
              >
                <AccordionTrigger className="text-sm px-4 py-3 hover:no-underline hover:bg-muted/30">
                  <div className="flex items-center gap-3 min-w-0 flex-1">
                    <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-muted shrink-0">
                      <cat.icon className="h-3.5 w-3.5 text-foreground/70" />
                    </div>
                    <div className="text-left min-w-0 flex-1">
                      <span className="font-medium block">{cat.label}</span>
                      <span className="text-[10px] text-muted-foreground">{cat.description}</span>
                    </div>
                    <div className="shrink-0 mr-2">
                      {cat.data.count > 0 ? (
                        <Badge variant="outline" className="gap-1 rounded-md text-[10px] border-success/30 text-success bg-success/5">
                          <CheckCircle2 className="h-3 w-3" />
                          {cat.data.count} dosya
                        </Badge>
                      ) : (
                        <Badge variant="outline" className="gap-1 rounded-md text-[10px] border-muted-foreground/30 text-muted-foreground">
                          Boş
                        </Badge>
                      )}
                    </div>
                  </div>
                </AccordionTrigger>
                <AccordionContent>
                  <div className="px-4 pb-4 pl-[60px] space-y-3">
                    {cat.data.count > 0 ? (
                      <>
                        <div className="flex items-center gap-1.5 text-[10px] text-muted-foreground font-mono mb-2">
                          <FolderOpen className="h-3 w-3 shrink-0" />
                          {cat.data.directory}/
                        </div>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-1">
                          {cat.data.files.map((file) => (
                            <div key={file} className="flex items-center gap-1.5 font-mono rounded-lg bg-muted/40 px-2.5 py-1.5 text-[11px]">
                              <cat.icon className="h-3 w-3 text-muted-foreground shrink-0" />
                              <span className="truncate">{file}</span>
                            </div>
                          ))}
                        </div>
                      </>
                    ) : (
                      <p className="text-xs text-muted-foreground">Bu kategoride derlenmiş dosya yok.</p>
                    )}
                  </div>
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        )}
      </div>
    </div>
  );
}
