import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { useAutoGeneratedContent } from "@/api/hooks";
import { FileCode2, AlertCircle, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useState, useCallback } from "react";
import Editor from "@monaco-editor/react";

interface FilePreviewDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  filePath: string | null;
  fileName: string | null;
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function getMonacoLanguage(fileName: string): string {
  if (fileName.endsWith(".xsl") || fileName.endsWith(".xslt")) return "xml";
  if (fileName.endsWith(".xml") || fileName.endsWith(".sch")) return "xml";
  if (fileName.endsWith(".xsd")) return "xml";
  if (fileName.endsWith(".json")) return "json";
  return "xml";
}

export function FilePreviewDialog({
  open,
  onOpenChange,
  filePath,
  fileName,
}: FilePreviewDialogProps) {
  const { data, isLoading, error } = useAutoGeneratedContent(
    open && filePath ? filePath : ""
  );
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    if (!data?.content) return;
    await navigator.clipboard.writeText(data.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [data?.content]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[90vw] max-h-[90vh] flex flex-col">
        <DialogHeader className="shrink-0">
          <div className="flex items-center gap-3">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-muted shrink-0">
              <FileCode2 className="h-4 w-4 text-foreground/70" />
            </div>
            <div className="min-w-0 flex-1">
              <DialogTitle className="text-sm font-semibold truncate">
                {fileName ?? "Dosya Önizleme"}
              </DialogTitle>
              <DialogDescription className="text-[10px] font-mono text-muted-foreground truncate">
                {filePath}
              </DialogDescription>
            </div>
            <div className="flex items-center gap-2 shrink-0">
              {data && (
                <Badge
                  variant="outline"
                  className="text-[10px] rounded-md font-mono"
                >
                  {formatBytes(data.size)}
                </Badge>
              )}
              <Button
                variant="ghost"
                size="sm"
                className="h-7 px-2 text-xs gap-1.5"
                onClick={handleCopy}
                disabled={!data?.content}
              >
                {copied ? (
                  <>
                    <Check className="h-3 w-3 text-success" />
                    Kopyalandı
                  </>
                ) : (
                  <>
                    <Copy className="h-3 w-3" />
                    Kopyala
                  </>
                )}
              </Button>
            </div>
          </div>
        </DialogHeader>

        <div className="flex-1 min-h-0 rounded-lg border overflow-hidden bg-[#1e1e1e]">
          {isLoading ? (
            <div className="p-6 space-y-3">
              {Array.from({ length: 12 }).map((_, i) => (
                <Skeleton
                  key={i}
                  className="h-4 bg-white/5"
                  style={{ width: `${40 + Math.random() * 55}%` }}
                />
              ))}
            </div>
          ) : error ? (
            <div className="flex items-center justify-center h-full p-8">
              <div className="flex items-start gap-3 text-destructive">
                <AlertCircle className="h-5 w-5 shrink-0 mt-0.5" />
                <div>
                  <p className="font-medium text-sm">Dosya yüklenemedi</p>
                  <p className="text-xs text-muted-foreground mt-1">
                    Dosya içeriği okunurken bir hata oluştu.
                  </p>
                </div>
              </div>
            </div>
          ) : data?.content ? (
            <Editor
              height="calc(80vh - 120px)"
              language={getMonacoLanguage(fileName ?? "")}
              value={data.content}
              theme="vs-dark"
              options={{
                readOnly: true,
                minimap: { enabled: true },
                fontSize: 12,
                lineNumbers: "on",
                wordWrap: "on",
                scrollBeyondLastLine: false,
                renderWhitespace: "selection",
                bracketPairColorization: { enabled: true },
                folding: true,
                foldingStrategy: "indentation",
                automaticLayout: true,
                domReadOnly: true,
                contextmenu: true,
                scrollbar: {
                  verticalScrollbarSize: 8,
                  horizontalScrollbarSize: 8,
                },
              }}
            />
          ) : null}
        </div>
      </DialogContent>
    </Dialog>
  );
}
